/*
Created to enable GSLC calls to be used from other files (unfortunately you cannot include the auto generated 
<projectname>_GLSC.h file in more than one place in your project or you get multiple declaration warnings.)
items are copied from autogenerated ApRemote_GSLC.h, and where needed, are changed to "extern"

This file will need manually updating from ApRemote_GSLC.h if changes are made to the GUI.

*/

#ifndef _GUISLICE_GEN_H
#define _GUISLICE_GEN_H

// ------------------------------------------------
// Headers to include
// ------------------------------------------------
#include "GUIslice.h"
#include "GUIslice_drv.h"

// Include any extended elements
//<Includes !Start!>
// Include extended elements
#include "elem/XCheckbox.h"
#include "elem/XSlider.h"
#include "elem/XTextbox.h"

//<Includes !End!>

// ------------------------------------------------
// Create element storage
// ------------------------------------------------
extern gslc_tsGui                      m_gui;
extern gslc_tsDriver                   m_drv;
extern gslc_tsFont                     m_asFont[];
extern gslc_tsPage                     m_asPage[];

// ------------------------------------------------
// Program Globals
// ------------------------------------------------

// Element References for direct access
//<Extern_References !Start!>
extern gslc_tsElemRef* m_pEleBtnWifiWifiInfo;
extern gslc_tsElemRef* m_pElemBrnBaseWiFi;
extern gslc_tsElemRef* m_pElemBtnAprAuto;
extern gslc_tsElemRef* m_pElemBtnAprMinusOne;
extern gslc_tsElemRef* m_pElemBtnAprMinusTen;
extern gslc_tsElemRef* m_pElemBtnAprPlusOne;
extern gslc_tsElemRef* m_pElemBtnAprPlusTen;
extern gslc_tsElemRef* m_pElemBtnAprPortTack;
extern gslc_tsElemRef* m_pElemBtnAprStandby;
extern gslc_tsElemRef* m_pElemBtnAprStbdTack;
extern gslc_tsElemRef* m_pElemBtnAprTrack;
extern gslc_tsElemRef* m_pElemBtnAprWind;
extern gslc_tsElemRef* m_pElemBtnBaseApr;
extern gslc_tsElemRef* m_pElemBtnBaseData;
extern gslc_tsElemRef* m_pElemBtnBaseDiag;
extern gslc_tsElemRef* m_pElemBtnWifiConfigureWifi;
extern gslc_tsElemRef* m_pElemBtnWifiResetWifi;
extern gslc_tsElemRef* m_pElemRadioButtonAprAuto;
extern gslc_tsElemRef* m_pElemRadioButtonAprStandby;
extern gslc_tsElemRef* m_pElemRadioButtonAprTrack;
extern gslc_tsElemRef* m_pElemRadioButtonAprWind;
extern gslc_tsElemRef* m_pElemTextboxAprDisplay;
extern gslc_tsElemRef* m_pElemTextboxDataDepth;
extern gslc_tsElemRef* m_pElemTextboxDataHdg;
extern gslc_tsElemRef* m_pElemTextboxDataSog;
extern gslc_tsElemRef* m_pElemTextboxDataSow;
extern gslc_tsElemRef* m_pElemTextboxDataWDir;
extern gslc_tsElemRef* m_pElemTextboxDataWind;
extern gslc_tsElemRef* m_pElemTextboxDiagLog;
extern gslc_tsElemRef* m_pElemTextboxStatus;
extern gslc_tsElemRef* m_pTextSlider10;
extern gslc_tsElemRef* m_pTextSlider11;
extern gslc_tsElemRef* m_pTextSlider4;
extern gslc_tsElemRef* m_pTextSlider4;
extern gslc_tsElemRef* m_pTextSlider4;
extern gslc_tsElemRef* m_pTextSlider4;
extern gslc_tsElemRef* m_pTextSlider4;
extern gslc_tsElemRef* m_pTextSlider4;
extern gslc_tsElemRef* m_pTextSliderDiagLog;
//<Extern_References !End!>

#endif // _GUISLICE_GEN_H